name: JOFD错误反馈
description: 提交与整合包相关的问题、建议或反馈
title: "[反馈]: "
labels:
  - 整合包
  - 问题类型
projects:
  - Journey-of-Forging-Dreams/issus
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        请尽可能简单的概括您遇到的问题或建议！（因为这是标题）

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: 须知
      description: 是否已经检查过了此问题没有重复。
      options:
        - label: 确认
          required: true


  - type: checkboxes
    id: code-of-conduct-1
    attributes:
      label: 须知
      description: 是正在使用最新版整合包。
      options:
        - label: 确认
          required: true

  - type: input
    id: modpack-version
    attributes:
      label: 整合包版本
      description: 您正在使用的整合包版本号。
      placeholder: 例如：1.0.0
    validations:
      required: true


  - type: dropdown
    id: issue-type
    attributes:
      label: 问题类型
      description: 请选择您提交的问题类型。
      options:
        - 功能请求
        - BUG
        - 崩溃
        - 其他
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 详细描述
      description: 请详细描述您遇到的问题或建议，包括具体的操作步骤、期望结果和实际结果，最好请提供截图或视频。
      placeholder: 例如：“xxx物品出现了bug...并没有实现xxx功能”
    validations:
      required: true


  - type: textarea
    id: logs
    attributes:
      label: 日志文件
      description: 请提供相关的日志文件内容（若是以文件的形式上传到详细描述部分也是可以的）
      render: shell
    validations:
      required: true
